#!/bin/bash
#$1 class name, $2 project compilation path, $3 project name, $4 package 

#generates tests using Evosuite for the current subject

full_class_package=$4.$1

output_dir=subjects/$3/src/test/java/
mkdir -p $output_dir        #create directory to save generated tests
rm -f $output_dir/evosuite-tests/**/*.java       #delete old tests if any

java -jar $EVOSUITE_JAR -class $full_class_package -projectCP $2 -Dsearch_budget=$EVOSUITE_TIME -Dstopping_condition=MaxTime -seed 1696864256417 -base_dir $output_dir

./scripts/utils/create_evosuite_tests_driver $output_dir $4 $1