#!/bin/bash
#$1 java file, $2 class name $3 method name, $4 subject, $5 used tool

#inserts the specifications generated by Daikon as assertions in the given subject

specs="generated_specs/$4/$5/$5_inv.txt"

#check that specifications file exists and it's not empty
if ! [ -f "$specs" ] || [ $(wc -c < "$specs") -le "1" ]; then
    echo -e "\n${RED}there are no specifications for $4 ${NORMAL}\n"
    exit
fi

#check that java classes are compiled, if not compile them
if [[ ! -d "/tmp/java_classes/" ]]; then
    echo "compiling assertion inserter classes"
    #.class file is sent to /tmp/java_classes/specs/
    find scripts/ -name "*.java" > resources/java_classes_to_compile.txt
    javac -cp libs/javaparser-core-3.25.5-SNAPSHOT.jar:libs/javaparser-symbol-solver-core-3.25.5-SNAPSHOT.jar -d /tmp/ @resources/java_classes_to_compile.txt

    if [ $? != 0 ]; then
        echo -e "\n${RED}couldn't compile some classes on scripts/utils/java/${NORMAL}\n"
        exit
    fi
fi

pre_cond=""
post_conds=("")
source scripts/utils/extract_specs.sh

#run AssertionInserter
java -cp /tmp/:libs/javaparser-core-3.25.5-SNAPSHOT.jar:libs/javaparser-symbol-solver-core-3.25.5-SNAPSHOT.jar java_classes/specs/MainController $1 $2 $3 "$pre_cond" "${post_conds[@]}"