#!/bin/bash

#creates and cleans the folder to store OASIs results for current iteration
function create_results_folder() {
    rm -r -f $tmp_output_dir        #clean results
    mkdir -p $tmp_output_dir
    log=$tmp_output_dir/OASIslog.txt
    touch $log
}

#returns all necesary libraries for the current subject as classpath
function add_libraries() {
    libraries=""

    local file_count=$(ls subjects/$1/libs/ | wc -l)
    if [ $file_count -eq "0" ]; then
        return
    fi

    for lib in subjects/$1/libs/*.jar; do
        if [ -z "$libraries" ]; then
            libraries="${PWD}/$lib"
        else
            libraries="${PWD}/$lib:$libraries"
        fi
    done
}

#cleans the directory from results left by previous executions of this script
function clean_old_results_on_first_iteration() {
    if [ $1 -eq 1 ]; then
        rm -r -f $output_dir
    fi
}

#delete temporal files generated by this script
function clean_temporal_files() {
    rm -r $PWD/tmp_results/
    rm $subjects_to_check
    rm $next_subjects_to_check
    rm tmp_subjects_swap_var.txt
}

#$1 indicates the testing tool used

#Runs OASIs over all subjects n times and keeps the most significant result
readonly NUMBER_OF_RUNS=3

if [[ $1 != "randoop" && $1 != "evosuite" ]]; then
    echo -e "\n\n\n${RED}invalid testing tool provided, expected randoop or evosuite, but received $1 ${NORMAL}\n"
    exit
fi

base_output_dir=$PWD/OASIs_results
#create a list of the subjects to analize
subjects_to_check=resources/subjects_to_check.txt
next_subjects_to_check=resources/next_subjects_to_check.txt
cp resources/subject_names.txt $next_subjects_to_check


file="$subjects_to_check"
IFS=';' #setting ; as delimiter
for i in {1..NUMBER_OF_RUNS}; do
    cp $next_subjects_to_check $subjects_to_check
    while read -ra line; do
        echo -e "\n\n\n${YELLOW}Checking false positives/negatives on ${line[0]} for ${i}th time${NORMAL}\n"
        
        assertions_file="assertions/${line[0]}/$1/${line[0]}.java"
        if [[ ! -f "$assertions_file" ]]; then
            echo -e "\n${RED}there are no assertions for ${line[0]} with $1${NORMAL}\n"
            continue
        fi
        
        package_as_path="$( echo "${line[1]}" | tr  '.' '/'  )"
        
        tmp_output_dir=$PWD/tmp_results/"${line[0]}"/$1
        log=""
        create_results_folder
        add_libraries "${line[0]}"
        
        cp "$assertions_file" "subjects/${line[0]}/src/main/java/$package_as_path/${line[2]}.java"
        bash scripts/utils/OASIs_mod.sh "${line[1]}.${line[2]}" "subjects/${line[0]}/src/main/java" "${line[3]}" "$tmp_output_dir" "$package_as_path" "$libraries" > $log
        cp "original_subject_classes/${line[0]}/${line[2]}.java" "subjects/${line[0]}/src/main/java/$package_as_path/${line[2]}.java"

        output_dir=$base_output_dir/"${line[0]}"/$1
        clean_old_results_on_first_iteration $i
        bash scripts/utils/check_OASIs_results.sh "$log" "$output_dir" "${line[0]}"
        check_results "${line[0]}"
    done <$file
done

clean_temporal_files