#!/bin/bash
#$1: package name, $2 project compilation path, $3 project name

output_dir=generated_tests/$3
mkdir -p $output_dir        #create directory to save generated tests
rm $output_dir/evosuite-tests/**/*.java       #delete old tests if any

java -jar $EVOSUITE_JAR -class $1 -projectCP $2 -Dsearch_budget=10 -Dstopping_condition=MaxTime -base_dir $output_dir