#!/bin/bash

file="scripts/pruebas_subject_names.txt"

IFS=';' #setting ; as delimiter
while read -ra line; do
    #arg 1 is package, arg 2 is project folder name, arg 3 is class to test
    ./scripts/generate_single_class_tests "${line[0]}" "${line[1]}" "${line[2]}"
done <$file