#!/bin/bash
#$1 project name, $2 package name, $3 class name, $4 the testing tool to use

project_root=$(pwd)
dir="$project_root/subjects/$1"

if [ ! -d "$dir/build" ]; then  #compile if not done yet
    cd $dir
    echo -n | ./gradlew -q -Dskip.tests jar
    cd $project_root
fi

full_class_package=$2.$3

#generate tests
if [ $4 == "randoop" ]; then
    project_classpath="$dir/build/libs/*:$dir/libs/*:"
    log=$dir/randoop_log.txt
    touch $log
    ./scripts/randoop_tests $full_class_package $project_classpath $1 $2 > $log 2>&1
elif [ $4 == "evosuite" ]; then
    project_compilation_path="$dir/build/classes/java/main/:$dir/build/libs/simple-examples-1.0-SNAPSHOT.jar:"
    log=$dir/evosuite_log.txt
    touch $log
    ./scripts/evosuite_tests $3 $project_compilation_path $1 $2 > $log 2>&1
else
    echo -e "\n\n\n${RED}invalid testing tool provided, expected randoop or evosuite, but received $4 ${NORMAL}\n"
fi
