#!/bin/bash

project_root=$(pwd)
dir="$project_root/pruebas/subjects/$2"
randoop_jar="libs/randoop-all-4.3.1.jar"

if [ ! -d "$dir/build" ]; then  #compile if not done yet
    cd $dir
    ./gradlew -q -Dskip.tests jar
    cd ../../
fi
    
project_classpath="$dir/build/libs/*:$dir/libs/*"
full_class_package=$1.$3

echo "${1}.${3}" > classlist.txt   #write main class in classlist file
#get class dependencies
jdeps -apionly -v -cp $project_classpath $full_class_package | grep -v '^[A-Za-z]' | sed -E 's/^.* -> ([^ ]+) .*$/\1/' | sort | uniq >> classlist.txt

output_dir=generated_tests/$2
mkdir -p $output_dir        #create directory to save generated tests
rm $output_dir/*.java       #delete old tests if any

java -classpath ${randoop_jar}:$project_classpath randoop.main.Main gentests --classlist=classlist.txt --time-limit=10 --junit-output-dir=$output_dir
