#!/bin/bash
#$1 project name, $2 package, $3 the testing tool used

cd subjects/$1/
./gradlew jar                #rebuild subject putting tests in jar
cd ../../

# javac -g -cp libs/junit-4.12.jar:hamcrest-core-1.3.jar -d subjects/$1/build/classes/java/main/org/apache/commons/math3/util subjects/$1/src/main/java/org/apache/commons/math3/util/*.java subjects/$1/src/test/evosuite-tests/org/apache/commons/math3/util/*.java subjects/$1/src/test/randoop/org/apache/commons/math3/util/*.java
subject_jar=subjects/$1/build/libs/simple-examples-1.0-SNAPSHOT.jar

output_dir=generated_specs/$1

if [ $3 == "randoop" ]; then
    output_dir=$output_dir/randoop
    mkdir -p $output_dir        #create directory to save generated specs
    rm $output_dir/*.dtrace.gz       #delete old specs if any

    java -cp $subject_jar:$DAIKONDIR/daikon.jar daikon.DynComp $2.RegressionTestDriver
    java -cp $subject_jar:$DAIKONDIR/daikon.jar daikon.Chicory --daikon --output-dir=$output_dir --comparability-file=RegressionTestDriver.decls-DynComp $2.RegressionTestDriver > /dev/null

    rm RegressionTestDriver.decls-DynComp
    mv RegressionTestDriver.inv.gz $output_dir/RegressionTestDriver.inv.gz

elif [ $3 == "evosuite" ]; then
    output_dir=$output_dir/evosuite
    mkdir -p $output_dir        #create directory to save generated specs
    rm $output_dir/*.dtrace.gz       #delete old specs if any

    java -cp $subject_jar:$DAIKONDIR/daikon.jar:libs/evosuite-standalone-runtime-1.0.6.jar daikon.DynComp $2.TestDriverEvosuite
    java -cp $subject_jar:$DAIKONDIR/daikon.jar daikon.Chicory --daikon --output-dir=$output_dir --comparability-file=TestDriverEvosuite.decls-DynComp $2.TestDriverEvosuite > /dev/null

    rm TestDriverEvosuite.decls-DynComp
    mv TestDriverEvosuite.inv.gz $output_dir/TestDriverEvosuite.inv.gz

else
    echo -e "\n\n\n${RED}invalid testing tool provided, expected randoop or evosuite, but received $3 ${NORMAL}\n"
fi