#!/bin/bash
#$1 indicates the testing tool to use

file="scripts/subject_names.txt"

if [[ $1 != "randoop" && $1 != "evosuite" ]]; then
    echo -e "\n\n\n${RED}invalid testing tool provided, expected randoop or evosuite, but received $1 ${NORMAL}\n"
    exit
fi

IFS=';' #setting ; as delimiter
while read -ra line; do
    echo -e "\n\n\n${YELLOW}generating tests for ${line[1]}\nparameters: ${line[1]}, ${line[0]}, ${line[2]}, ${line[3]} ${NORMAL}\n"
    ./scripts/generate_single_class_tests "${line[1]}" "${line[0]}" "${line[2]}" $1 < /dev/null
    ./scripts/generate_daikon_specs "${line[1]}" "${line[0]}" "${line[2]}" "${line[3]}" $1 < /dev/null
done <$file
